export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED";
export const SEND_MESSAGE_FINISHED = "SEND_MESSAGE_FINISHED";

export const CHANGE_CHATBOT = "CHANGE_CHATBOT";
export const CHANGE_ROUTE = "CHANGE_ROUTE";
